using System.Collections.Immutable;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using NUnit.Framework;
using Rebellion.Analyzers;

namespace Rebellion.Analyzers.Tests
{
    [TestFixture]
    public sealed class MemberDeclarationOrderAnalyzerTests
    {
        [Test]
        public async Task FieldAfterMethod_ReportsDiagnosticAsync()
        {
            const string source =
                @"
class Example
{
    void Render() { }
    private int _value;
}";

            ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source);

            Assert.AreEqual(1, diagnostics.Length);
            Assert.AreEqual(MemberDeclarationOrderAnalyzer.DiagnosticId, diagnostics[0].Id);
        }

        [Test]
        public async Task FieldBeforeMethod_DoesNotReportDiagnosticAsync()
        {
            const string source =
                @"
class Example
{
    private int _value;
    void Render() { }
}";

            ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source);

            Assert.IsEmpty(diagnostics);
        }

        [Test]
        public async Task FieldAfterNestedMethod_ReportsDiagnosticAsync()
        {
            const string source =
                @"
class Outer
{
    class Inner
    {
        void Render() { }
        private int _value;
    }
}";

            ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source);

            Assert.AreEqual(1, diagnostics.Length);
            Assert.AreEqual(MemberDeclarationOrderAnalyzer.DiagnosticId, diagnostics[0].Id);
        }

        [Test]
        public async Task GeneratedCode_DoesNotReportDiagnosticAsync()
        {
            const string source =
                @"
// <auto-generated/>
class Example
{
    void Render() { }
    private int _value;
}";

            ImmutableArray<Diagnostic> diagnostics = await AnalyzeAsync(source);

            Assert.IsEmpty(diagnostics);
        }

        private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(string source)
        {
            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(source);
            MetadataReference coreLibrary = MetadataReference.CreateFromFile(
                typeof(object).Assembly.Location
            );
            CSharpCompilation compilation = CSharpCompilation.Create(
                "AnalyzerTests",
                new[] { syntaxTree },
                new[] { coreLibrary },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            );
            ImmutableArray<DiagnosticAnalyzer> analyzers =
                ImmutableArray.Create<DiagnosticAnalyzer>(new MemberDeclarationOrderAnalyzer());

            return await compilation.WithAnalyzers(analyzers).GetAnalyzerDiagnosticsAsync();
        }
    }
}
