using System.Collections.Generic;
using Rebellion.AI.Director;
using Rebellion.Game.Galaxy;
using Rebellion.Game.Units;
using Rebellion.SceneGraph;

namespace Rebellion.AI.Planners.Demand
{
    /// <summary>
    /// Production demand categories generated by the AI.
    /// </summary>
    public enum AIDemandKind
    {
        None,
        Colony,
        Mine,
        Refinery,
        ConstructionFacility,
        Shipyard,
        TrainingFacility,
        PlanetaryDefense,
        PlanetaryStarfighterReserve,
        FleetCapitalShip,
        FleetStarfighter,
        FleetRegiment,
        GarrisonRegimentReserve,
        SpecialForces,
        FleetSeedCapitalShip,
        BuildingUpgrade,
    }

    /// <summary>
    /// Strategic roles that a capital ship can fill for a production demand.
    /// </summary>
    public enum AICapitalShipProductionRole
    {
        /// <summary>No specialized role is required.</summary>
        None,

        /// <summary>The ship contributes general fleet combat power.</summary>
        General,

        /// <summary>The ship transports regiments for planetary assaults.</summary>
        TroopTransport,

        /// <summary>The ship can bombard planetary defenses.</summary>
        Bombardment,

        /// <summary>The ship prevents hostile fleets from retreating.</summary>
        Interdiction,
    }

    /// <summary>
    /// Represents one AI production need.
    /// </summary>
    public sealed class AIDemand
    {
        /// <summary>
        /// Creates a production demand.
        /// </summary>
        /// <param name="id">Stable demand identifier.</param>
        /// <param name="kind">Demand kind.</param>
        /// <param name="manufacturingType">Manufacturing type required for the demand.</param>
        /// <param name="buildingType">Building type required for building demands.</param>
        /// <param name="destination">Container receiving the produced item.</param>
        /// <param name="quantityNeeded">Amount of demand still needed.</param>
        /// <param name="pressure">Demand pressure used for scoring.</param>
        /// <param name="productTypeId">Exact product type required by the demand.</param>
        /// <param name="capitalShipRole">Capital ship role required by the demand.</param>
        public AIDemand(
            string id,
            AIDemandKind kind,
            ManufacturingType manufacturingType,
            BuildingType buildingType,
            ContainerNode destination,
            int quantityNeeded,
            double pressure,
            string productTypeId = null,
            AICapitalShipProductionRole capitalShipRole = AICapitalShipProductionRole.None
        )
        {
            Id = id;
            Kind = kind;
            ManufacturingType = manufacturingType;
            BuildingType = buildingType;
            Destination = destination;
            QuantityNeeded = quantityNeeded;
            Pressure = pressure;
            ProductTypeId = productTypeId;
            CapitalShipRole = capitalShipRole;
        }

        // Demand Identity.
        public string Id { get; }
        public AIDemandKind Kind { get; }

        // Production Requirements.
        public ManufacturingType ManufacturingType { get; }
        public BuildingType BuildingType { get; }
        public string ProductTypeId { get; }
        public AICapitalShipProductionRole CapitalShipRole { get; }
        public Building BuildingToReplace { get; set; }

        // Destination.
        public ContainerNode Destination { get; }
        public Planet DestinationPlanet => Destination as Planet;
        public Fleet DestinationFleet => Destination as Fleet;

        // Priority.
        public int QuantityNeeded { get; }
        public double Pressure { get; }

        // Reserve Policy.
        public bool CanUseRefinedMaterialReserve =>
            Kind
                is AIDemandKind.Mine
                    or AIDemandKind.Refinery
                    or AIDemandKind.TrainingFacility
                    or AIDemandKind.FleetRegiment
                    or AIDemandKind.GarrisonRegimentReserve;

        public bool UsesDefensiveReserve =>
            Kind
                is AIDemandKind.PlanetaryDefense
                    or AIDemandKind.PlanetaryStarfighterReserve
                    or AIDemandKind.GarrisonRegimentReserve
                    or AIDemandKind.TrainingFacility
                    or AIDemandKind.BuildingUpgrade;

        /// <summary>
        /// Builds the canonical demand identifier for a faction, kind, and key parts.
        /// </summary>
        /// <param name="factionInstanceId">The owning faction instance id.</param>
        /// <param name="kind">The demand kind.</param>
        /// <param name="parts">Additional identifier segments.</param>
        /// <returns>The canonical demand identifier.</returns>
        internal static string CreateId(
            string factionInstanceId,
            AIDemandKind kind,
            params object[] parts
        )
        {
            string id = $"production:{factionInstanceId}:{kind}";
            foreach (object part in parts)
                id += $":{part}";

            return id;
        }
    }

    /// <summary>
    /// Base type for a generator-owned source of production demand.
    /// </summary>
    internal abstract class AIDemandSource
    {
        /// <summary>
        /// Adds demand from this source to the production plan.
        /// </summary>
        /// <param name="context">The current AI turn context.</param>
        /// <param name="demands">The demand collection to update.</param>
        internal abstract void AddDemands(AITurnContext context, ICollection<AIDemand> demands);
    }
}
