using Rebellion.Game.Galaxy;
using Rebellion.Game.Units;
using Rebellion.SceneGraph;

namespace Rebellion.AI.Demands
{
    /// <summary>
    /// Production demand categories generated by the AI.
    /// </summary>
    public enum AIProductionDemandKind
    {
        None,
        Colony,
        Mine,
        Refinery,
        ConstructionFacility,
        Shipyard,
        TrainingFacility,
        PlanetaryDefense,
        PlanetaryStarfighterReserve,
        FleetCapitalShip,
        FleetStarfighter,
        FleetRegiment,
        GarrisonRegimentReserve,
        SpecialForces,
        FleetSeedCapitalShip,
        ColonizationFleetSeedCapitalShip,
        BuildingUpgrade,
    }

    /// <summary>
    /// Strategic roles that a capital ship can fill for a production demand.
    /// </summary>
    public enum AICapitalShipProductionRole
    {
        None,

        General,

        TroopTransport,

        Bombardment,

        Interdiction,
    }

    /// <summary>
    /// Represents one AI production need.
    /// </summary>
    public sealed class AIProductionDemand
    {
        // Demand Identity.
        public string Id { get; }
        public AIProductionDemandKind Kind { get; }

        // Production Capability.
        public ManufacturingType ManufacturingType { get; }
        public BuildingType BuildingType { get; }
        public string ProductTypeId { get; }
        public AICapitalShipProductionRole CapitalShipRole { get; }
        public Building BuildingToReplace { get; }

        // Destination.
        public ContainerNode Destination { get; }
        public Planet DestinationPlanet => Destination as Planet;
        public Fleet DestinationFleet => Destination as Fleet;

        // Measured Need.
        public int QuantityNeeded { get; }
        public int DeficitCount { get; }
        public int TargetCount { get; }
        public int BaseDemandPercent { get; }
        public Planet ReferencePlanet { get; }
        public bool EstablishesInitialShield { get; }

        // Reserve Policy.
        public bool CanUseRefinedMaterialReserve =>
            Kind
                is AIProductionDemandKind.Mine
                    or AIProductionDemandKind.Refinery
                    or AIProductionDemandKind.ColonizationFleetSeedCapitalShip
            || DestinationFleet?.RoleType == FleetRoleType.Colonization;

        public bool UsesDefensiveReserve =>
            Kind
                is AIProductionDemandKind.PlanetaryDefense
                    or AIProductionDemandKind.PlanetaryStarfighterReserve
                    or AIProductionDemandKind.GarrisonRegimentReserve
                    or AIProductionDemandKind.TrainingFacility
                    or AIProductionDemandKind.BuildingUpgrade;

        public bool RestoresMaintenanceCapacity =>
            Kind is AIProductionDemandKind.Mine or AIProductionDemandKind.Refinery;

        /// <summary>
        /// Creates a production demand.
        /// </summary>
        /// <param name="id">Stable demand identifier.</param>
        /// <param name="kind">Demand kind.</param>
        /// <param name="manufacturingType">Manufacturing type required for the demand.</param>
        /// <param name="buildingType">Building type required for building demands.</param>
        /// <param name="destination">Container receiving the produced item.</param>
        /// <param name="quantityNeeded">Amount of demand still needed.</param>
        /// <param name="productTypeId">Exact product type required by the demand.</param>
        /// <param name="capitalShipRole">Capital ship role required by the demand.</param>
        /// <param name="buildingToReplace">Existing building replaced by an upgrade.</param>
        /// <param name="targetCount">Total capability target used to measure the deficit.</param>
        /// <param name="baseDemandPercent">Configured base urgency before scored considerations.</param>
        /// <param name="referencePlanet">Planet whose unmet need prompted this demand.</param>
        /// <param name="establishesInitialShield">Whether this demand establishes a planet's first shield.</param>
        /// <param name="deficitCount">Original unmet quantity before proposal batching.</param>
        public AIProductionDemand(
            string id,
            AIProductionDemandKind kind,
            ManufacturingType manufacturingType,
            BuildingType buildingType,
            ContainerNode destination,
            int quantityNeeded,
            string productTypeId = null,
            AICapitalShipProductionRole capitalShipRole = AICapitalShipProductionRole.None,
            Building buildingToReplace = null,
            int targetCount = 0,
            int baseDemandPercent = 0,
            Planet referencePlanet = null,
            bool establishesInitialShield = false,
            int deficitCount = 0
        )
        {
            Id = id;
            Kind = kind;
            ManufacturingType = manufacturingType;
            BuildingType = buildingType;
            Destination = destination;
            QuantityNeeded = quantityNeeded;
            DeficitCount = deficitCount > 0 ? deficitCount : quantityNeeded;
            TargetCount = targetCount;
            BaseDemandPercent = baseDemandPercent;
            ReferencePlanet = referencePlanet;
            EstablishesInitialShield = establishesInitialShield;
            ProductTypeId = productTypeId;
            CapitalShipRole = capitalShipRole;
            BuildingToReplace = buildingToReplace;
        }

        /// <summary>
        /// Copies this demand with a different immediately requested quantity.
        /// </summary>
        /// <param name="quantityNeeded">Quantity represented by the copied demand.</param>
        /// <returns>A demand with identical strategic identity and requirements.</returns>
        internal AIProductionDemand WithQuantity(int quantityNeeded)
        {
            return new AIProductionDemand(
                Id,
                Kind,
                ManufacturingType,
                BuildingType,
                Destination,
                quantityNeeded,
                ProductTypeId,
                CapitalShipRole,
                BuildingToReplace,
                TargetCount,
                BaseDemandPercent,
                ReferencePlanet,
                EstablishesInitialShield,
                DeficitCount
            );
        }

        /// <summary>
        /// Builds the canonical demand identifier for a faction, kind, and key parts.
        /// </summary>
        /// <param name="factionInstanceId">The owning faction instance id.</param>
        /// <param name="kind">The demand kind.</param>
        /// <param name="parts">Additional identifier segments.</param>
        /// <returns>The canonical demand identifier.</returns>
        internal static string CreateId(
            string factionInstanceId,
            AIProductionDemandKind kind,
            params object[] parts
        )
        {
            string id = $"production:{factionInstanceId}:{kind}";
            foreach (object part in parts)
                id += $":{part}";

            return id;
        }
    }
}
