using Rebellion.Game.Galaxy;
using Rebellion.Game.Units;
using Rebellion.SceneGraph;

namespace Rebellion.AI.Planners
{
    /// <summary>
    /// Production demand categories generated by the AI.
    /// </summary>
    public enum AIDemandKind
    {
        None,
        Colony,
        Mine,
        Refinery,
        ConstructionFacility,
        Shipyard,
        TrainingFacility,
        PlanetaryDefense,
        PlanetaryStarfighterReserve,
        FleetCapitalShip,
        FleetStarfighter,
        FleetRegiment,
        GarrisonRegimentReserve,
        SpecialForces,
        FleetSeedCapitalShip,
        ColonizationFleetSeedCapitalShip,
        BuildingUpgrade,
    }

    /// <summary>
    /// Strategic roles that a capital ship can fill for a production demand.
    /// </summary>
    public enum AICapitalShipProductionRole
    {
        None,

        General,

        TroopTransport,

        Bombardment,

        Interdiction,
    }

    /// <summary>
    /// Represents one AI production need.
    /// </summary>
    public sealed class AIDemand
    {
        // Demand Identity.
        public string Id { get; }
        public AIDemandKind Kind { get; }

        // Production Requirements.
        public ManufacturingType ManufacturingType { get; }
        public BuildingType BuildingType { get; }
        public string ProductTypeId { get; }
        public AICapitalShipProductionRole CapitalShipRole { get; }
        public Building BuildingToReplace { get; }

        // Destination.
        public ContainerNode Destination { get; }
        public Planet DestinationPlanet => Destination as Planet;
        public Fleet DestinationFleet => Destination as Fleet;

        // Priority.
        public int QuantityNeeded { get; }
        public double Pressure { get; }

        // Reserve Policy.
        public bool CanUseRefinedMaterialReserve =>
            Kind
                is AIDemandKind.Mine
                    or AIDemandKind.Refinery
                    or AIDemandKind.ColonizationFleetSeedCapitalShip
            || DestinationFleet?.RoleType == FleetRoleType.Colonization;

        public bool UsesDefensiveReserve =>
            Kind
                is AIDemandKind.PlanetaryDefense
                    or AIDemandKind.PlanetaryStarfighterReserve
                    or AIDemandKind.GarrisonRegimentReserve
                    or AIDemandKind.TrainingFacility
                    or AIDemandKind.BuildingUpgrade;

        public bool RestoresMaintenanceCapacity =>
            Kind is AIDemandKind.Mine or AIDemandKind.Refinery;

        /// <summary>
        /// Creates a production demand.
        /// </summary>
        /// <param name="id">Stable demand identifier.</param>
        /// <param name="kind">Demand kind.</param>
        /// <param name="manufacturingType">Manufacturing type required for the demand.</param>
        /// <param name="buildingType">Building type required for building demands.</param>
        /// <param name="destination">Container receiving the produced item.</param>
        /// <param name="quantityNeeded">Amount of demand still needed.</param>
        /// <param name="pressure">Demand pressure used for scoring.</param>
        /// <param name="productTypeId">Exact product type required by the demand.</param>
        /// <param name="capitalShipRole">Capital ship role required by the demand.</param>
        /// <param name="buildingToReplace">Existing building replaced by an upgrade.</param>
        public AIDemand(
            string id,
            AIDemandKind kind,
            ManufacturingType manufacturingType,
            BuildingType buildingType,
            ContainerNode destination,
            int quantityNeeded,
            double pressure,
            string productTypeId = null,
            AICapitalShipProductionRole capitalShipRole = AICapitalShipProductionRole.None,
            Building buildingToReplace = null
        )
        {
            Id = id;
            Kind = kind;
            ManufacturingType = manufacturingType;
            BuildingType = buildingType;
            Destination = destination;
            QuantityNeeded = quantityNeeded;
            Pressure = pressure;
            ProductTypeId = productTypeId;
            CapitalShipRole = capitalShipRole;
            BuildingToReplace = buildingToReplace;
        }

        /// <summary>
        /// Copies this demand with a different immediately requested quantity.
        /// </summary>
        /// <param name="quantityNeeded">Quantity represented by the copied demand.</param>
        /// <returns>A demand with identical strategic identity and requirements.</returns>
        internal AIDemand WithQuantity(int quantityNeeded)
        {
            return new AIDemand(
                Id,
                Kind,
                ManufacturingType,
                BuildingType,
                Destination,
                quantityNeeded,
                Pressure,
                ProductTypeId,
                CapitalShipRole,
                BuildingToReplace
            );
        }

        /// <summary>
        /// Builds the canonical demand identifier for a faction, kind, and key parts.
        /// </summary>
        /// <param name="factionInstanceId">The owning faction instance id.</param>
        /// <param name="kind">The demand kind.</param>
        /// <param name="parts">Additional identifier segments.</param>
        /// <returns>The canonical demand identifier.</returns>
        internal static string CreateId(
            string factionInstanceId,
            AIDemandKind kind,
            params object[] parts
        )
        {
            string id = $"production:{factionInstanceId}:{kind}";
            foreach (object part in parts)
                id += $":{part}";

            return id;
        }
    }
}
