using Rebellion.Game.Galaxy;
using Rebellion.Game.Units;
using Rebellion.SceneGraph;

namespace Rebellion.AI.Planners
{
    /// <summary>
    /// Production demand categories generated by the AI.
    /// </summary>
    public enum AIProductionDemandKind
    {
        None,
        Mine,
        Refinery,
        ConstructionFacility,
        Shipyard,
        TrainingFacility,
        PlanetaryDefense,
        PlanetaryStarfighterReserve,
        FleetCapitalShip,
        FleetStarfighter,
        FleetRegiment,
        GarrisonRegimentReserve,
        SpecialForces,
        FleetSeedCapitalShip,
        BuildingUpgrade,
    }

    public enum AICapitalShipProductionRole
    {
        None,
        General,
        TroopTransport,
        Bombardment,
    }

    /// <summary>
    /// Represents one AI production need.
    /// </summary>
    public sealed class AIProductionDemand
    {
        /// <summary>
        /// Creates a production demand.
        /// </summary>
        /// <param name="id">Stable demand identifier.</param>
        /// <param name="kind">Demand kind.</param>
        /// <param name="manufacturingType">Manufacturing type required for the demand.</param>
        /// <param name="buildingType">Building type required for building demands.</param>
        /// <param name="destination">Container receiving the produced item.</param>
        /// <param name="quantityNeeded">Amount of demand still needed.</param>
        /// <param name="pressure">Demand pressure used for scoring.</param>
        /// <param name="productTypeId">Exact product type required by the demand.</param>
        /// <param name="capitalShipRole">Capital ship role required by the demand.</param>
        public AIProductionDemand(
            string id,
            AIProductionDemandKind kind,
            ManufacturingType manufacturingType,
            BuildingType buildingType,
            ContainerNode destination,
            int quantityNeeded,
            double pressure,
            string productTypeId = null,
            AICapitalShipProductionRole capitalShipRole = AICapitalShipProductionRole.None
        )
        {
            Id = id;
            Kind = kind;
            ManufacturingType = manufacturingType;
            BuildingType = buildingType;
            Destination = destination;
            QuantityNeeded = quantityNeeded;
            Pressure = pressure;
            ProductTypeId = productTypeId;
            CapitalShipRole = capitalShipRole;
        }

        public string Id { get; }
        public AIProductionDemandKind Kind { get; }
        public ManufacturingType ManufacturingType { get; }
        public BuildingType BuildingType { get; }
        public ContainerNode Destination { get; }
        public Planet DestinationPlanet => Destination as Planet;
        public Fleet DestinationFleet => Destination as Fleet;
        public int QuantityNeeded { get; }
        public double Pressure { get; }
        public string ProductTypeId { get; }
        public AICapitalShipProductionRole CapitalShipRole { get; }
        public Building ReplacementBuilding { get; set; }
        public bool UsesDefensiveReserve =>
            Kind
                is AIProductionDemandKind.PlanetaryDefense
                    or AIProductionDemandKind.PlanetaryStarfighterReserve
                    or AIProductionDemandKind.GarrisonRegimentReserve
                    or AIProductionDemandKind.TrainingFacility
                    or AIProductionDemandKind.BuildingUpgrade;
    }
}
