<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Unity omits package-owned test assemblies from generated test projects. -->
  <ItemGroup>
    <Reference Include="Unity.InputSystem.TestFramework">
      <HintPath>$(MSBuildProjectDirectory)/Library/ScriptAssemblies/Unity.InputSystem.TestFramework.dll</HintPath>
    </Reference>
    <Reference Include="UnityEditor.TestRunner">
      <HintPath>$(MSBuildProjectDirectory)/Library/ScriptAssemblies/UnityEditor.TestRunner.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TestRunner">
      <HintPath>$(MSBuildProjectDirectory)/Library/ScriptAssemblies/UnityEngine.TestRunner.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
