name: Unity Editmode Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Run Unity Tests
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 2022.3.43f1
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          dockerCpuLimit: 2
          dockerMemoryLimit: 8g

      # Discard Unity package resolution changes
      - name: Reset package files
        run: |
          git checkout -- Packages/manifest.json Packages/packages-lock.json 2>/dev/null || true
          sudo rm -rf artifacts || true

      # Build the Unity project
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 2022.3.43f1
          targetPlatform: StandaloneWindows64
